# Generated by Django 4.1.4 on 2022-12-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, null=True)),
                ("price", models.IntegerField(null=True)),
                ("image", models.CharField(max_length=300, null=True)),
                ("release_date", models.CharField(max_length=50, null=True)),
                ("lte_exists", models.BooleanField(null=True)),
                ("slug", models.SlugField(null=True, unique=True)),
            ],
        ),
    ]
